# Generated by Django 3.2 on 2024-09-02 20:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyTaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('due_date', models.DateField(db_index=True, default=datetime.date(2024, 9, 2))),
                ('reminder_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='home.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_date',),
                'unique_together': {('user', 'title')},
            },
        ),
    ]
