# Generated by Django 5.1.1 on 2024-09-03 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 20, 46, 51, 486168, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 20, 46, 51, 486184, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='mytasklist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 20, 46, 51, 486168, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AlterField(
            model_name='mytasklist',
            name='due_date',
            field=models.DateField(db_index=True, default=datetime.date(2024, 9, 3)),
        ),
        migrations.AlterField(
            model_name='mytasklist',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 20, 46, 51, 486184, tzinfo=datetime.timezone.utc)),
        ),
    ]
